// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMa54nOaAX6YH3iFKNCnJwGxhb9Xc_FXI',
    appId: '1:562135749285:web:b8ae73f18375333231334c',
    messagingSenderId: '562135749285',
    projectId: 'arabic-srs',
    authDomain: 'arabic-srs.firebaseapp.com',
    storageBucket: 'arabic-srs.firebasestorage.app',
    measurementId: 'G-8DG32LMBWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRSu2lcqzr2NUUGUqo2xEKOcDBSkh9wbY',
    appId: '1:562135749285:android:5770475b12454edf31334c',
    messagingSenderId: '562135749285',
    projectId: 'arabic-srs',
    storageBucket: 'arabic-srs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADBrbg60StzhaShxCre8KNN6P7R1lI7xM',
    appId: '1:562135749285:ios:e89644c8b6a9c4e131334c',
    messagingSenderId: '562135749285',
    projectId: 'arabic-srs',
    storageBucket: 'arabic-srs.firebasestorage.app',
    iosBundleId: 'com.example.arabicSrs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADBrbg60StzhaShxCre8KNN6P7R1lI7xM',
    appId: '1:562135749285:ios:e89644c8b6a9c4e131334c',
    messagingSenderId: '562135749285',
    projectId: 'arabic-srs',
    storageBucket: 'arabic-srs.firebasestorage.app',
    iosBundleId: 'com.example.arabicSrs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMa54nOaAX6YH3iFKNCnJwGxhb9Xc_FXI',
    appId: '1:562135749285:web:fe3aa3841863b2e331334c',
    messagingSenderId: '562135749285',
    projectId: 'arabic-srs',
    authDomain: 'arabic-srs.firebaseapp.com',
    storageBucket: 'arabic-srs.firebasestorage.app',
    measurementId: 'G-FPLZNZ4HP2',
  );
}
